app = "shaikbot786"  # ← unique app name (tu khud ka daale)

[build]
  image = "python:3.11-slim"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
